server:
  port: 9001

eureka:
  client:
    serviceUrl:

      defaultZone: http://localhost:9000/eureka/

spring:
  application:

    name: login-service
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456

    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.hxd.loginservice.entity